
#spring:
  #静态资源访问前缀
  #mvc:
  #  static-path-pattern: /res/**
  #修改静态资源存取路径
  #web:
  #  resources:
  #    static-locations:
  #      - classpath:

#开启请求参数内容协商器(即支持在请求参数中携带内容类型,如: xxx/xxx?format=xml : 浏览器接收xml类型数据)
spring:
  mvc:
    contentnegotiation:
      favor-parameter: true

  #指标监控图形化服务器地址
  boot:
    admin:
      client:
        url: http://localhost:8888
        instance:
          prefer-ip: true     #使用IP注册
  # 项目名
  application:
    name: WebView


  #redis数据缓存
  redis:
    url: redis://localhost:6379
    #redis客户端类型默认为lettuce(另一个是jedis)
    #client-type: lettuce
    #lettuce:
    #  #资源池配置
    #  pool:
    #    max-active: 8
    #    min-idle: 5


  #数据源配置
  datasource:
    #数据库连接信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_user
    username: root
    password: 123456
    #阿里巴巴德鲁伊数据源
    druid:
      aop-patterns: com.fausto.fan.app.*  #监控SpringBean
      filters: stat,wall     # 底层开启功能，stat（sql监控），wall（防火墙）

      stat-view-servlet:   # 配置监控页功能
        enabled: true
        login-username: admin
        login-password: admin
        resetEnable: false

      web-stat-filter:  # 监控web
        enabled: true
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      filter:
        stat:    # 对上面filters里面的stat的详细配置
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false



#Mybatis相关配置
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml          #映射文件位置
  configuration:                                            #替代mybatis全局配置文件
    map-underscore-to-camel-case: true                      #开启下划线转驼峰命名


#management 是所有 Actuator 的配置
management:
  #配置所有端点
  endpoints:
    enabled-by-default: true #默认开启所有监控端点
    web:
      exposure:
        include: '*' #以web方式暴露所有端点
  #配置单个端点
  endpoint:
    #开启health端点
    health:
      enabled: true
      show-details: always #开启health端点的详细信息显示
    #开启info端点
    info:
      enabled: true
    #开启beans端点
    beans:
      enabled: true
    #开启指标端点
    metrics:
      enabled: true


#自定义Info信息,可从指标信息中获取: /actuator/info
info:
  appName: Fausto_Web
  appVersion: 1.0.0